### ISSUE TITLE
Writing match log to kafka is not robust

### ISSUE THREAD

**Issue by yihuang** [gitbitex/gitbitex-spot#11]
I think current way of writing to kafka is not robust, in case of match engine crash, some log messages not yet written into kafka successfully may lost.

**Comment by greensheng** [comment]
We have considered the case of process crash. Through the snapshot mechanism to ensure that any log will not be lost, when the process is restarted, a snapshot recovery will be done. Therefore, there will be no data loss, but duplicate logs will be generated.

**Comment by yihuang** [comment]
Thanks for your reply and work. Let me elaborate a bit: 
1、Do you ensure that when snapshotting, all the messages produced to kafka get acked?
2、AFAIK kafka producer doesn't guarantee message order, does that impact the following processes.

**Comment by greensheng** [comment]
> Thanks for your reply and work. Let me elaborate a bit:
> 1、Do you ensure that when snapshotting, all the messages produced to kafka get acked?
> 2、AFAIK kafka producer doesn't guarantee message order, does that impact the following processes.

1，Yes, We use synchronous write to submit logs, writing 1000 logs at a time.When we save the snapshot, we will first check whether the **snapshot.logSeq** has been submitted to Kafka.
2，Only one partition is used for each log topic, so the sequence can be guaranteed.

**Comment by yihuang** [comment]
2, The retry behavior in the producer side will change the order of messages.

**Comment by greensheng** [comment]
> 2, The retry behavior in the producer side will change the order of messages.

Log producer is synchronous and single thread, and there will be no concurrent submission.

**Comment by yihuang** [comment]
https://stackoverflow.com/questions/49007592/kafka-message-ordering-in-partition-while-producer-retry

**Comment by greensheng** [comment]
I see what you mean. I read the source code of Kafka go. Retrying really leads to the order not being guaranteed.

At present, if the log consumer finds the log.seq discontinuity, it will terminate the process.

Do you think enable. idempotence can solve this problem?

**Comment by yihuang** [comment]
Yes, `enable.idempotence = true` suppose to solve this, if kafka go is a binding to librdkafka.
