### ISSUE TITLE
Guide install

### ISSUE THREAD

**Issue by letienmanhtn** [gitbitex/gitbitex-spot#12]
Can you provide detailed installation instructions?

**Comment by greensheng** [comment]
**### Install**

**Server**
git clone https://github.com/gitbitex/gitbitex-spot.git
Create database and make sure BINLOG[ROW format] enabled
Execute ddl.sql
Modify conf.json
Run go build
Run ./gitbitex-spot

**Web**
git clone https://github.com/gitbitex/gitbitex-web.git
Run npm install
Run npm start
Run npm run build to build production
