### ISSUE TITLE
Database initialize sql ?

### ISSUE THREAD

**Issue by wuleiLonghe** [gitbitex/gitbitex-spot#2]
Tks！

**Comment by greensheng** [comment]
edit conf.json , set enableAutoMigrate=true.

**Comment by wuleiLonghe** [comment]
Ok.Tks, I got it.
The front page open source?

**Comment by greensheng** [comment]
> Ok.Tks, I got it.
> The front page open source?

Yes, But we need to do some changes to make sure we don't break the law, because our UI mimics the [coinbase pro]
See : https://gitbitex.com:8080/trade/BTC-USDT
