### ISSUE TITLE
Guide 

### ISSUE THREAD

**Issue by ProfProfcompile** [gitbitex/gitbitex-spot#3]
Hi Dev 

Is there a quick instruction guide of starting your platform by any chance . 

Thanks

**Comment by greensheng** [comment]
> Hi Dev
> 
> Is there a quick instruction guide of starting your platform by any chance .
> 
> Thanks

## INSTALL
*  Create mysql database, and make sure **binlog(ROW format)** enabled
* Install Redis
* Install Kafka
* git clone https://github.com/gitbitex/gitbitex-spot.git
* Run: go build
* Edit conf.json, set enableAutoMigrate=true
* Run: ./gitbitex-sopt
* Insert some products into your database:
```sql
insert into `g_product`(`id`,`created_at`,`updated_at`,`base_currency`,`quote_currency`,`base_min_size`,`base_max_size`,`base_scale`,`quote_scale`,`quote_increment`,`quote_min_size`,`quote_max_size`) values
('BTC-USDT',null,null,'BTC','USDT',0.0000100000000000,10000000.0000000000000000,6,2,0.01,null,null);
```
* Restart gitbitex-spot
* Done
