### ISSUE TITLE
JWT Token Error 

### ISSUE THREAD

**Issue by safebuffer** [gitbitex/gitbitex-spot#4]
https://github.com/gitbitex/gitbitex-spot/blob/d6521d23d433c83e28152ecc8ea2370879a6ff8b/conf/gbe_config.go#L28 

```golang
JwtSecret  string           `json:"jwtSecret"` // "jwtSecret" not same as key in the conf.json , which is "jwtToken"
```
https://github.com/gitbitex/gitbitex-spot/blob/d6521d23d433c83e28152ecc8ea2370879a6ff8b/conf.json#L26

**Comment by greensheng** [comment]
FIXED
