### ISSUE TITLE
并发貌似有点问题呀

### ISSUE THREAD

**Issue by dotcool** [gitbitex/gitbitex-spot#5]
用户注册

我用jmeter测试是2500

下单接口

{
	"client_oid":"a053c079-5370-4817-8cd9-67d4587e7b7f",
	"productId":"BCH-USDT",
	"size":0.001,
	"funds":0.00001,
	"price":1,
	"side":"buy",
	"type":"limit",
	"timeInForce":"1"
}

类似这样的数据，200都会卡住，请问大佬能否看一下。

**Comment by greensheng** [comment]
请问你部署的服务器配置和数据库配置是什么样的？系统的瓶颈基本上都在IO，特别是MySQL。

**Comment by dotcool** [comment]
服务器配置挺好的，16G。我感觉不是本身问题，还是在执行快照那里的问题
