### ISSUE TITLE
我每秒20个下单，然后程序挂了

### ISSUE THREAD

**Issue by dotcool** [gitbitex/gitbitex-spot#7]
kMessage:{matching_message_BCH-USDT 0 51 [] [123 34 84 121 112 101 34 58 34 111 112 101 110 34 44 34 83 101 113 117 101 110 99 101 34 58 51 52 52 51 44 34 80 114 111 100 117 99 116 73 100 34 58 34 66 67 72 45 85 83 68 84 34 44 34 84 105 109 101 34 58 34 50 48 49 57 45 48 57 45 51 48 84 49 50 58 48 50 58 53 54 46 56 55 54 48 50 56 55 43 48 56 58 48 48 34 44 34 79 114 100 101 114 73 100 34 58 55 48 51 51 44 34 82 101 109 97 105 110 105 110 103 83 105 122 101 34 58 34 48 46 48 48 49 34 44 34 80 114 105 99 101 34 58 34 49 34 44 34 83 105 100 101 34 58 34 98 117 121 34 125] [] 2019-09-30 12:02:56.882 +0800 CST}[2019/09/30 12:08:04] [fatal] kafka_log_reader.go:81 non-sequence detected, lastSeq=51 seq=3443

**Comment by greensheng** [comment]
log序列号发生了不连续，要确认一下redis里面的快照和kafka的log得数据是一致的。一般是redis里面存的snapshot的数据不一致。

**Comment by dotcool** [comment]
单已用户每秒20个订单，执行了大概1个小时
ret:brpop g_bill 1000: MISCONF Redis is configured to save RDB snapshots, but it is currently not able to persist on disk. Commands that may modify the data set are disabled, because this instance is configured to report errors during writes if RDB snapshotting fails (stop-writes-on-bgsave-error option). Please check the Redis logs for details about the RDB error.
[2019/09/30 14:12:32] [error] bill_executor.go:77 MISCONF Redis is configured to save RDB snapshots, but it is currently not able to persist on disk. Commands that may modify the data set are disabled, because this instance is configured to report errors during writes if RDB snapshotting fails (stop-writes-on-bgsave-error option). Please check the Redis logs for details about the RDB error.

提示这个错误

**Comment by dotcool** [comment]
redis也要设置这个，不然启动不了

config set stop-writes-on-bgsave-error no

**Comment by dotcool** [comment]
![image](https://user-images.githubusercontent.com/6111056/65854415-24e00380-e38f-11e9-96c0-d62554f70869.png)

我重启应用，就会不断打印kafka的这个消息队列发过来的消息。
系统也没法正常响应

**Comment by greensheng** [comment]
你的redis有问题，先确保redis能正常工作。

**Comment by dotcool** [comment]
redis和数据库都是内网centos哦。没有在windows部署哈。redis可以正常工作呢，给你截图你看里面就有redis的呢

**Comment by dotcool** [comment]
![image](https://user-images.githubusercontent.com/6111056/65862343-a12f1280-e3a0-11e9-8f1f-a4c6979428c2.png)
我这边的kafka的manager。请问是否出现了问题。因为我这边还是不断的从kafka里面啦信息，疯狂打印

**Comment by greensheng** [comment]
x可以先看一下redis里面的快照数据的orderoffset值是多少

**Comment by greensheng** [comment]
可以看一下redis里面保存的快照的orderoffset是多少。
